import { useEffect, useState } from "react";
import { api, type Me } from "../lib/api";

type Member = { id: string; email: string; displayName: string; role: "owner" | "admin" | "member"; teamWikiRole: "editor" | "user" };
type Usage = { totals: { requests: number; successful: number; inputTokens: number; outputTokens: number; estimatedCost: string; averageLatencyMs: number }; byUser: Array<{ userId: string; displayName: string; email: string; requests: number; inputTokens: number; outputTokens: number; estimatedCost: string }> };
type Skill = { id: string; slug: string; name: string; description: string; instructions: string; enabled: boolean };

export function SettingsPanel({ me, onChanged }: { me: Me; onChanged: () => Promise<void> }) {
  const org = me.organizations.find((item) => item.id === me.activeOrgId)!;
  const [displayName, setDisplayName] = useState(org.displayName);
  const [personalWikiEnabled, setPersonalWikiEnabled] = useState(org.personalWikiEnabled);
  const [members, setMembers] = useState<Member[]>([]);
  const [saved, setSaved] = useState(false);
  const [invite, setInvite] = useState({ email: "", displayName: "", temporaryPassword: "", teamWikiRole: "user" as "user" | "editor" });
  const [newOrg, setNewOrg] = useState({ slug: "", displayName: "" });
  const [usage, setUsage] = useState<Usage | null>(null);
  const [skills, setSkills] = useState<Skill[]>([]);
  const [skillDraft, setSkillDraft] = useState({ slug: "", name: "", description: "", instructions: "" });
  useEffect(() => { void Promise.all([api<{ members: Member[] }>("/api/organizations/current/members"), api<Usage>("/api/admin/usage"), api<{ skills: Skill[] }>("/api/skills")]).then(([memberResult, usageResult, skillResult]) => { setMembers(memberResult.members); setUsage(usageResult); setSkills(skillResult.skills); }); }, []);
  async function saveOrg() { await api("/api/organizations/current", { method: "PATCH", body: JSON.stringify({ displayName, personalWikiEnabled }) }); setSaved(true); await onChanged(); setTimeout(() => setSaved(false), 1600); }
  async function updateMember(member: Member, teamWikiRole: "editor" | "user") { await api(`/api/organizations/current/members/${member.id}`, { method: "PATCH", body: JSON.stringify({ teamWikiRole }) }); setMembers((rows) => rows.map((row) => row.id === member.id ? { ...row, teamWikiRole } : row)); }
  async function addMember() { const result = await api<{ member: Member }>("/api/organizations/current/members", { method: "POST", body: JSON.stringify(invite) }); setMembers((rows) => [...rows, result.member]); setInvite({ email: "", displayName: "", temporaryPassword: "", teamWikiRole: "user" }); }
  async function createOrganization() { await api("/api/organizations", { method: "POST", body: JSON.stringify(newOrg) }); await onChanged(); window.location.reload(); }
  async function createSkill() { const result = await api<{ skill: Skill }>("/api/skills", { method: "POST", body: JSON.stringify(skillDraft) }); setSkills((rows) => [...rows, result.skill]); setSkillDraft({ slug: "", name: "", description: "", instructions: "" }); }
  async function toggleSkill(skill: Skill) { const result = await api<{ skill: Skill }>(`/api/skills/${skill.id}`, { method: "PATCH", body: JSON.stringify({ enabled: !skill.enabled }) }); setSkills((rows) => rows.map((row) => row.id === skill.id ? result.skill : row)); }
  return <section className="panel-page settings-page"><header className="panel-header"><div><h1>组织设置</h1><p>设置组织名称和知识权限</p></div></header>
    {usage && <div className="usage-grid"><div><span>近 30 天请求</span><strong>{usage.totals.requests}</strong></div><div><span>成功率</span><strong>{usage.totals.requests ? Math.round(usage.totals.successful / usage.totals.requests * 100) : 0}%</strong></div><div><span>总 Token</span><strong>{(Number(usage.totals.inputTokens) + Number(usage.totals.outputTokens)).toLocaleString()}</strong></div><div><span>估算成本</span><strong>${Number(usage.totals.estimatedCost).toFixed(4)}</strong></div></div>}
    <div className="settings-card"><h2>基本信息</h2><label>平台显示名称<input value={displayName} onChange={(e) => setDisplayName(e.target.value)} /></label><label className="switch-row"><span><strong>允许个人知识库</strong><small>成员可以创建只有自己可见的 Wiki</small></span><input type="checkbox" checked={personalWikiEnabled} onChange={(e) => setPersonalWikiEnabled(e.target.checked)} /></label><button className="primary-small" onClick={() => void saveOrg()}>{saved ? "已保存" : "保存更改"}</button></div>
    <div className="settings-card"><h2>成员知识权限</h2><div className="member-table">{members.map((member) => <div className="member-row" key={member.id}><div className="member-avatar">{member.displayName.slice(0, 1)}</div><div className="member-name"><strong>{member.displayName}</strong><span>{member.email}</span></div><span className="role-chip">{member.role === "owner" ? "所有者" : member.role === "admin" ? "管理员" : "成员"}</span><select value={member.teamWikiRole} disabled={member.role !== "member"} onChange={(e) => void updateMember(member, e.target.value as "editor" | "user")}><option value="user">仅使用团队知识</option><option value="editor">可编辑团队知识</option></select></div>)}</div></div>
    {usage && <div className="settings-card"><h2>成员用量</h2><div className="usage-table">{usage.byUser.map((row) => <div key={row.userId}><span><strong>{row.displayName}</strong><small>{row.email}</small></span><span>{row.requests} 次</span><span>{(Number(row.inputTokens) + Number(row.outputTokens)).toLocaleString()} tokens</span><span>${Number(row.estimatedCost).toFixed(4)}</span></div>)}</div></div>}
    <div className="settings-card"><h2>组织 Skill</h2><p className="settings-hint">启用后，Codex 会在当前组织的隔离工作区发现并按需使用这些操作说明。</p><div className="skill-list">{skills.map((skill) => <div key={skill.id}><span><strong>{skill.name}</strong><small>{skill.description}</small></span><button className="secondary-button" onClick={() => void toggleSkill(skill)}>{skill.enabled ? "已启用" : "已停用"}</button></div>)}</div><div className="skill-form"><div className="form-grid"><label>标识<input value={skillDraft.slug} onChange={(e) => setSkillDraft({ ...skillDraft, slug: e.target.value.toLowerCase() })} placeholder="meeting-summary" /></label><label>名称<input value={skillDraft.name} onChange={(e) => setSkillDraft({ ...skillDraft, name: e.target.value })} /></label></div><label>使用场景<input value={skillDraft.description} onChange={(e) => setSkillDraft({ ...skillDraft, description: e.target.value })} placeholder="当用户需要整理会议记录时使用" /></label><label>操作说明<textarea rows={7} value={skillDraft.instructions} onChange={(e) => setSkillDraft({ ...skillDraft, instructions: e.target.value })} /></label><button className="primary-small" onClick={() => void createSkill()}>添加 Skill</button></div></div>
    <div className="settings-card"><h2>添加成员</h2><div className="form-grid"><label>姓名<input value={invite.displayName} onChange={(e) => setInvite({ ...invite, displayName: e.target.value })} /></label><label>邮箱<input type="email" value={invite.email} onChange={(e) => setInvite({ ...invite, email: e.target.value })} /></label><label>临时密码<input type="password" value={invite.temporaryPassword} onChange={(e) => setInvite({ ...invite, temporaryPassword: e.target.value })} placeholder="至少 10 位" /></label><label>团队知识权限<select value={invite.teamWikiRole} onChange={(e) => setInvite({ ...invite, teamWikiRole: e.target.value as "user" | "editor" })}><option value="user">仅使用</option><option value="editor">可编辑</option></select></label></div><button className="primary-small" onClick={() => void addMember()}>添加成员</button></div>
    {me.user.isSuperAdmin && <div className="settings-card"><h2>创建新组织</h2><p className="settings-hint">仅平台超级管理员可创建。新组织的数据和知识与当前组织完全隔离，你会成为所有者。</p><div className="form-grid"><label>组织标识<input value={newOrg.slug} onChange={(e) => setNewOrg({ ...newOrg, slug: e.target.value.toLowerCase() })} placeholder="organization-b" /></label><label>显示名称<input value={newOrg.displayName} onChange={(e) => setNewOrg({ ...newOrg, displayName: e.target.value })} /></label></div><button className="secondary-button" onClick={() => void createOrganization()}>创建组织</button></div>}
  </section>;
}
